remote_theme: just-the-docs/just-the-docs
# baseurl: "/documentation"
title: "Core Documentation"
author: "speedrobotics@louisville.edu"
description: "The Redbird Robotics documentation site."
favicon_png: "/assets/images/favicon.png"
# nav_categories:
#   - GitHub
#   - Standards
